// This file is automatically generated. Do not edit it directly.
import type { Database } from './types';

const _PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImthbXNkdHhzdW5ubHdvZnZpd3lrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MTI3MDUsImV4cCI6MjA2NDI4ODcwNX0.AIIB3q18WSZ4auvMDpSHwlnTARfYaF-7S8rZRpWKr_M";


